/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_MESSAGE_H_RPCGEN
#define _RPC_MESSAGE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct PrintArgs {
	char operation[256];
	char username[256];
	char date[256];
	char file[256];
};
typedef struct PrintArgs PrintArgs;

#define SERVER_OPERATION 99
#define SERVER_OPERATION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define print 0
extern  enum clnt_stat print_1(struct PrintArgs , void *, CLIENT *);
extern  bool_t print_1_svc(struct PrintArgs , void *, struct svc_req *);
extern int server_operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print 0
extern  enum clnt_stat print_1();
extern  bool_t print_1_svc();
extern int server_operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PrintArgs (XDR *, PrintArgs*);

#else /* K&R C */
extern bool_t xdr_PrintArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_MESSAGE_H_RPCGEN */
