/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_message.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_1(struct PrintArgs args, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, print,
		(xdrproc_t) xdr_PrintArgs, (caddr_t) &args,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
