/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_message.h"

bool_t
xdr_PrintArgs (XDR *xdrs, PrintArgs *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->operation, 256))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->username, 256))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->date, 256))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->file, 256))
		 return FALSE;
	return TRUE;
}
