/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_message.h"
#include <string.h>
//Función rpc para imprimir los argumentos
bool_t
print_1_svc(struct PrintArgs args, void *result,  struct svc_req *rqstp)
{
	
	bool_t retval;
	//Si operación es publish o delete se imprime el nombre de archivo también
	if ((strcmp(args.operation,"PUBLISH")==0)||(strcmp(args.operation,"DELETE"))==0){
			
			printf("%s      %s       %s        %s\n",args.username,args.operation,args.file,args.date);
	}
	else{
		printf("%s      %s        %s\n",args.username,args.operation,args.date);
	}
	retval=TRUE;
	return retval;
}

int
server_operation_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
